# Generated by Django 4.2.7 on 2023-11-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_categories_employees_events_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'такой email адрес уже зарегистрирован'}, help_text='Введите ваш Email', max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
